name: Publish package to GitHub Packages
on: 
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
        with:
          tag_name: v1.2.0
          release_name: Release 1.2.0
          body: |
            Release notes for version 1.2.0.
          draft: false
          prerelease: false
      
      - name: Upload release asset
        uses: actions/upload-release-asset@v1.2.0
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/*.jar
          asset_name: My JAR File
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
          
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
